//   ********************
//   *** CLASS STRING ***
//   ********************


#ifndef string_hxx

#include <string.h>


/*
  This file implements functions for character string manipulations
  (comparison, concatenation, conversion).
*/

  char*  concatenate (char*,int,char*) ;
  char*  ctos (char,char*) ;
  int    isInteger (char*) ;
  int    isNumber (char*) ;
  char*  itos (int,char*) ;


#define string_hxx
#endif








